import Grid from "@mui/material/Grid";
import Paper from "@mui/material/Paper";
import { useState } from "react";
import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
import Button from "@mui/material/Button";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";

// axios
import api from "../../../../api/axios";

// hooks
import { useAuthContext } from "./../../../../hooks/useAuthContext";

export default function Doctor() {
  const { user } = useAuthContext();
  const [records, setRecords] = useState([]);
  const [searchEmail, setSearchEmail] = useState("");
  const [renderForm, setRenderForm] = useState(false);
  const [comments, setComments] = useState("");
  const [tests, setTests] = useState([]);
  const [index, setIndex] = useState(null);

  const handlePatientSearch = async e => {
    e.preventDefault();
    try {
      const response = await api.get(`/staff/history/${encodeURIComponent(searchEmail)}`).then(userData => {
        setRecords(userData.data.medical_records);
      });
    } catch (err) {
      console.log(`Error : ${err.message}`);
    }
  };

  const handleTestDetailsSubmit = async e => {
    e.preventDefault();
    const testArray = tests.split(",");
    var splitTestArray = testArray.map(function (test) {
      var box = test.split("-");
      return { name: box[0], result: box[1] };
    });

    try {
      const data = { index, email: searchEmail, comments, tests: splitTestArray, generated_by: user.name };
      const response = await api.post("/staff/labassistant", data).then(userData => {
        setRenderForm(false);
        setTests([]);
        setComments("");
      });
    } catch (err) {
      console.log(`Error : ${err.message}`);
    }
  };

  const handleEdit = e => {
    setIndex(e.target.value);
    setTests([]);
    setComments("");
    setRenderForm(true);
  };

  return (
    <Grid item xs={12} md={12} lg={12}>
      <Paper
        sx={{
          p: 2,
          display: "flex",
          flexDirection: "column",
          height: "auto",
        }}
      >
        <h2 className="dashboard-title">Lab Assistant Portal</h2>
        <Box component="form" onSubmit={handlePatientSearch} sx={{ mt: 2, mb: 2 }}>
          <TextField
            margin="normal"
            required
            fullWidth
            id="searchEmail"
            label="Patient Email Address"
            name="searchEmail"
            autoComplete="searchEmail"
            autoFocus
            onChange={e => setSearchEmail(e.target.value)}
            value={searchEmail}
          />

          <Button type="submit" variant="contained" sx={{ mt: 3, mb: 2 }}>
            Search
          </Button>
        </Box>
        {renderForm && (
          <Box component="form" onSubmit={handleTestDetailsSubmit} sx={{ mt: 2, mb: 2 }}>
            <TextField
              id="outlined-multiline-flexible"
              label="Comments"
              fullWidth
              multiline
              value={comments}
              onChange={e => setComments(e.target.value)}
              helperText="Add additional comments for the test report"
              maxRows={5}
              required
              sx={{ mb: 2, mt: 2 }}
            />
            <TextField
              id="outlined-multiline-flexible"
              label="[TestName1-TestResult1,TestName2-TestResult2,...]"
              fullWidth
              multiline
              value={tests}
              onChange={e => setTests(e.target.value)}
              helperText="Add names of tests conducted followed by their result (seperated by commas)"
              maxRows={5}
              required
              sx={{ mb: 2, mt: 2 }}
            />

            <Button type="submit" variant="contained" sx={{ mt: 3, mb: 2 }}>
              Update Test Report
            </Button>
          </Box>
        )}
        {records && (
          <TableContainer>
            <Table sx={{ minWidth: 650 }} aria-label="simple table">
              <TableHead>
                <TableRow>
                  <TableCell align="center">Record Id</TableCell>
                  <TableCell align="center">Comments</TableCell>
                  <TableCell align="center">Generated By</TableCell>
                  <TableCell align="center">Test Names</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {records.map((record, index) => (
                  <TableRow key={index} sx={{ "&:last-child td, &:last-child th": { border: 0 } }}>
                    <TableCell align="center">{record._id}</TableCell>
                    <TableCell align="center">{record.test_report.comments}</TableCell>
                    <TableCell align="center">{record.test_report.generated_by}</TableCell>
                    <TableCell align="center">{record.test_report.tests.map(test => test.name + " ")}</TableCell>
                    <TableCell align="center">
                      <Button onClick={handleEdit} name="edit" value={index}>
                        Edit
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        )}
      </Paper>
    </Grid>
  );
}
